#------------------------------------- PACKAGE SPECIFICATIONS -------------------------------------#

[package]
name = "launch-nvim"
version = "1.0.0"
edition = "2021"
authors = ["Dasu Pradyumna"]

[lib]
name = "launch"
crate-type = ["cdylib"]

[dependencies.nvim-oxi]
git = "https://github.com/noib3/nvim-oxi"
rev = "6a2483cb4dee72272a8f08d8807ba96d07f33947"
features = ["neovim-nightly", "libuv"]

[dependencies]
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
