#------------------------------------- PACKAGE SPECIFICATIONS -------------------------------------#

[package]
name = "launch-nvim"
version = "0.1.0"
edition = "2021"
authors = ["Dasu Pradyumna"]

[lib]
name = "launch"
crate-type = ["cdylib"]

[dependencies]
# CHECK: wait for v0.5.2, refer to "https://github.com/noib3/nvim-oxi/issues/202"
# nvim-oxi = { version = "0.5", features = ["neovim-nightly"] }
nvim-oxi = { path = "/home/pradyumna/foss/nvim-oxi", features = ["neovim-nightly"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
