### Config for "stylua" formatter

call_parentheses = 'None'
collapse_simple_statement = 'Always'
column_width = 100
indent_type = 'Spaces'
indent_width = 2
line_endings = 'Unix'
quote_style = 'AutoPreferSingle'
